sudo: required

services:
  - docker

before_install:
  - docker build -t mrkotte/loginapp ./loginapp

script:
  #Run tests instead of starting the server
  - docker run mrkotte/loginapp npm test

after_success:
  - docker build -t mrkotte/loginapp-nginx ./nginx

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take above build images and push them to docker hub
  - docker push mrkotte/loginapp
  - docker push mrkotte/loginapp-nginx

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: multi-docker-login
  env: MultiDockerLogin-env
  bucket_name: elasticbeanstalk-eu-north-1-679022722124
  bucket_path: multi-docker-login
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY